run: Add the option of running with Limine.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,21 +1,224 @@
 #!/bin/sh
 # SPDX-License-Identifier: MIT
 
+# Provide a variable if it is not already defined
+provide() {
+	if [ "$(eval echo \$$1)" == "" ]; then
+		eval "$1=$2"
+	fi
+}
+
+if [ -f .env ]; then
+	. ./.env
+fi
+
+provide LIMINE_BIN_DIR /usr/share/limine
+provide LIMINE_DEPLOY /usr/bin/limine-deploy
+
+provide OVMF_PATH "/usr/share/ovmf/x64"
+
+_help() {
+	echo "Usage: $0 [options]"
+	echo 'options:'
+	echo '  -h, --help                       Show this information.'
+	echo ''
+	echo '  -d, --debug                      Equivalent of `qemu-system-x86_64 -S -s`.'
+	echo ''
+	echo '  -X <option>                      Pass <option> directly to QEMU.'
+	echo ''
+	echo '  -m, --mem=<memory>               Set the amount of memory provided to a guest.'
+	echo '                                   (default: 256M)'
+	echo ''
+	echo '      --kvm                        Enable KVM acceleration of the guest. (enabled'
+	echo '                                   by default)'
+	echo '      --no-kvm                     Disable KVM acceleration of the guest.'
+	echo ''
+	echo '      --cpu=<cpu>                  Select CPU model of the guest.'
+	echo ''
+	echo '      --smp=<smp>                  Equivalent to QEMU -smp option.'
+	echo ''
+	echo '      --reboot={normal,shutdown}   Machine reboot action, also affects triple'
+	echo '                                   faults. (default: shutdown)'
+	echo ''
+	echo '      --bios'
+	echo '      --uefi'
+	echo '      --firmware={BIOS, UEFI}      Switch between BIOS and UEFI firmware.'
+	echo '                                   (default: UEFI)'
+	echo '                                   By default, OVMF firmware is searched for in'
+	echo '                                   the directory "/usr/share/ovmf/x64". This can'
+	echo '                                   be overridden by providing the environment'
+	echo '                                   variable "OVMF_PATH".'
+	echo ''
+	echo '      --grub'
+	echo '      --limine'
+	echo '      --bootloader={grub, limine}  Switch between GRUB and Limine as the'
+	echo '                                   bootloader used to build the kernel image.'
+	echo '                                   (default: GRUB)'
+}
+
+getopt -T
+if [ $? -ne 4 ]; then
+	echo "GNU enhanced getopt(1) is required for long options support." >&2
+	exit 1
+fi
+
+TEMP=$(getopt -o 'hdX:m:' --long 'help,debug,kvm,no-kvm,cpu:,smp:,mem:,reboot:,bios,uefi,firmware:,grub,limine,bootloader:' -n "$0" -- "$@")
+if [ $? -ne 0 ]; then
+	_help >&2
+	exit 1
+fi
+
+eval set -- "$TEMP"
+unset TEMP
+
+provide DEBUG "n"
+provide USE_KVM "y"
+provide QMEM "256M"
+provide QEXTRA ""
+provide QCPU "host"
+provide NO_REBOOT "y"
+provide FIRMWARE "UEFI"
+provide QSMP "1"
+provide BOOTLOADER "grub"
+
+while true; do
+	case "$1" in
+		'-h'|'--help')
+			_help >&2
+			exit 1
+		;;
+		'-d'|'--debug')
+			DEBUG="y"
+			shift
+		;;
+		'-X')
+			QEXTRA="$QEXTRA $2"
+			shift 2
+		;;
+		'--kvm')
+			USE_KVM='y'
+			shift
+		;;
+		'--no-kvm')
+			USE_KVM='n'
+			shift
+		;;
+		'--cpu')
+			QCPU="$2"
+			shift 2
+		;;
+		'--smp')
+			QSMP="$2"
+			shift 2
+		;;
+		'-m'|'--mem')
+			QMEM="$2"
+			shift 2
+		;;
+		'--reboot')
+			if [ "$2" == "normal" ]; then
+				NO_REBOOT="n"
+			elif [ "$2" == "shutdown" ]; then
+				NO_REBOOT="y"
+			else
+				echo "Unrecognized reboot behaviour: \"$2\"" >&2
+				_help
+				exit 1
+			fi
+			shift 2
+		;;
+		'--bios')
+			FIRMWARE="BIOS"
+			shift
+		;;
+		'--uefi')
+			FIRMWARE='UEFI'
+			shift
+		;;
+		'--firmware')
+			case "$2" in
+				'bios'|'BIOS')
+					FIRMWARE="BIOS"
+				;;
+				'uefi'|'UEFI')
+					FIRMWARE="UEFI"
+				;;
+				*)
+					echo "Unrecognized firmware type: \"$2\" (supported are: bios, uefi)" >&2
+					_help >&2
+					exit 1
+				;;
+			esac
+			shift 2
+		;;
+		'--grub')
+			BOOTLOADER="grub"
+			shift
+		;;
+		'--limine')
+			BOOTLOADER="limine"
+			shift
+		;;
+		'--bootloader')
+			case "$2" in
+				'grub'|'GRUB')
+					BOOTLOADER='grub'
+				;;
+				'limine'|'Limine')
+					BOOTLOADER='limine'
+				;;
+				*)
+					echo "Unrecognized bootloader: \"$2\"" >&2
+					exit 1
+				;;
+			esac
+			shift 2
+		;;
+		'--')
+			shift
+			break
+		;;
+		*)
+			echo "getopt(1) error (Are you using the GNU enhanced version?)" >&2
+			exit 1
+		;;
+	esac
+done
+
+QEMU_COMMAND="qemu-system-x86_64"
+
+if [ $USE_KVM = "y" ]; then
+	QEMU_COMMAND="$QEMU_COMMAND -enable-kvm"
+fi
+
+if [ $NO_REBOOT = "y" ]; then
+	QEMU_COMMAND="$QEMU_COMMAND -no-reboot"
+fi
+
+if [ $FIRMWARE = "UEFI" ]; then
+	QEMU_COMMAND="$QEMU_COMMAND -drive file=$OVMF_PATH/OVMF.fd,if=pflash,index=0,read-only=on"
+fi
+
+QEMU_COMMAND="$QEMU_COMMAND -m $QMEM -cpu $QCPU -smp $QSMP -cdrom /tmp/bootable-davix.iso -serial stdio -nic none"
+
+if [ $DEBUG = "y" ]; then
+	QEMU_COMMAND="$QEMU_COMMAND -S -s"
+fi
+
 set -e
-
-QCMD=$(tools/gen_qemu_cmd.sh -X "-cdrom /tmp/bootable-davix.iso" -X "-serial stdio" -X "-nic none" $@)
-
 make # build the kernel (and davix-multiboot2)
 
 if [ -d /tmp/isodir.davix ]; then
 	rm -r /tmp/isodir.davix
 fi
 
-mkdir -p /tmp/isodir.davix/boot/grub
-
+mkdir /tmp/isodir.davix
 cp build/davix-multiboot2 /tmp/isodir.davix/davix-multiboot2
-cat << EOF >> /tmp/isodir.davix/boot/grub/grub.cfg
 
+case $BOOTLOADER in
+	'grub')
+		mkdir -p /tmp/isodir.davix/boot/grub
+		cat << EOF >> /tmp/isodir.davix/boot/grub/grub.cfg
 insmod fat
 insmod efi_gop
 
@@ -30,5 +233,26 @@ menuentry "Davix" {
 }
 
 EOF
-grub-mkrescue -o /tmp/bootable-davix.iso /tmp/isodir.davix 2>/dev/null
-$QCMD | tools/format_serial.sh
+		grub-mkrescue -o /tmp/bootable-davix.iso /tmp/isodir.davix 2>/dev/null
+	;;
+	'limine')
+		cat << EOF >> /tmp/isodir.davix/limine.cfg
+TIMEOUT=1
+
+:Davix
+	PROTOCOL=multiboot2
+	KERNEL_PATH=boot:///davix-multiboot2
+
+EOF
+		cp $LIMINE_BIN_DIR/limine-cd.bin /tmp/isodir.davix/
+		cp $LIMINE_BIN_DIR/limine-cd-efi.bin /tmp/isodir.davix/
+		cp $LIMINE_BIN_DIR/limine.sys /tmp/isodir.davix/
+		xorriso -as mkisofs -b limine-cd.bin -no-emul-boot -boot-load-size 4 \
+			-boot-info-table --efi-boot limine-cd-efi.bin -efi-boot-part \
+			--efi-boot-image --protective-msdos-label /tmp/isodir.davix \
+			-o /tmp/bootable-davix.iso 2>/dev/null
+		$LIMINE_DEPLOY /tmp/bootable-davix.iso 2>/dev/null
+	;;
+esac
+
+$QEMU_COMMAND | tools/format_serial.sh
